import type { FC, ReactNode } from "react";

interface LayoutProps {
  children: ReactNode;
}

export const metadata = {
  title: "blog detail",
  description: "Generated by create next app",
};

const Layout: FC<LayoutProps> = ({ children }) => {
  return (
    <div>
      <h1>header only in blog detail page</h1>
      <div>{children}</div>
      <footer>footer only in blog detail page</footer>
    </div>
  );
};

export default Layout;
